{
  imports = [
    ./bootloader.nix
    ./sound.nix
    ./env.nix
    ./user.nix
    ./nm.nix
    ./bluetooth.nix
    ./polkit.nix
    ./solaar.nix
    ./gvfs.nix
    ./firmware.nix
    ./auto-cpufreq.nix
    ./systemd-resolved.nix
    ./kde.nix
    ./flatpak.nix
    ./ssh.nix
    ./virtualization.nix
    ./postgre.nix
  ];
}
